# Generated by Django 5.1.5 on 2025-01-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(upload_to='visitor_photos/')),
                ('face_encoding', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
