# Generated by Django 4.2.18 on 2025-02-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'مراجعه کننده', 'verbose_name_plural': ' مراجعه کنندگان'},
        ),
        migrations.AddField(
            model_name='visitor',
            name='company',
            field=models.CharField(default='ab', max_length=100, verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='family',
            field=models.CharField(default='blalala', max_length=100, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='nationalCode',
            field=models.IntegerField(default=12345, verbose_name='کدملی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
