# Generated by Django 4.2.18 on 2025-02-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='مدیر'),
        ),
    ]
